### ISSUE TITLE
can not run with this plugin NPE

### ISSUE THREAD

**Issue by vio-lin** [zengkid/SmartTomcat#120]
**Describe the bug**

add web app and click run ，
it is a error reported when i run application. 

Error running 'localTomcat' java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.setAttribute(String, String)" because "portE" is null

**Screenshots**
![image](https://github.com/zengkid/SmartTomcat/assets/12695349/54927b85-be4d-4dd8-b4bd-ee76d636113c)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**

ieda : 2023.3.2 (Community Edition)
SmartTomcat Version : 4.7.0

java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.setAttribute(String, String)" because "portE" is null
	at com.poratu.idea.plugins.tomcat.conf.TomcatCommandLineState.createJavaParameters(TomcatCommandLineState.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:133)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecute$2(DefaultJavaProgramRunner.java:123)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$patchJavaCommandLineParamsUnderProgress$2(JavaProgramPatcher.java:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:287)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.setAttribute(String, String)" because "portE" is null
	at com.poratu.idea.plugins.tomcat.conf.TomcatCommandLineState.updateServerConf(TomcatCommandLineState.java:200)
	at com.poratu.idea.plugins.tomcat.conf.TomcatCommandLineState.createJavaParameters(TomcatCommandLineState.java:129)
	... 35 more

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。

**Comment by yuezk** [comment]
Same as #114, has been fixed in the master branch. I'm releasing a new version.

**Comment by yuezk** [comment]
4.7.1 released, pending approval, it will be available in 24 hours. Remember to check the updates. Closing.
