### ISSUE TITLE
Cannot add Tomcat server 9.0.33

### ISSUE THREAD

**Issue by bcwood123** [zengkid/SmartTomcat#54]
I tried to add a new server, I pointed to apache-tomcat-9.0.33 directory, but it does not get added
![Screen Shot 2020-09-08 at 1 51 21 PM](https://user-images.githubusercontent.com/10818036/92526786-e4157f00-f1da-11ea-86f4-34b423f58334.png)
![Screen Shot 2020-09-08 at 1 51 33 PM](https://user-images.githubusercontent.com/10818036/92526805-e972c980-f1da-11ea-9e52-9e848cbd69c8.png)
![Screen Shot 2020-09-08 at 1 51 41 PM](https://user-images.githubusercontent.com/10818036/92526826-f1cb0480-f1da-11ea-9d72-e12359865657.png)

**Comment by zengkid** [comment]
@bcwood123 Could you get error log? 
I can't download 9.0.33, but work 9.0.35
![image](https://user-images.githubusercontent.com/3382739/92718680-b7a56280-f394-11ea-8b6c-4b8782cda31f.png)

**Comment by bcwood123** [comment]
2020-09-10 07:06:20,282 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------
2020-09-10 07:06:20,289 [      7]   INFO - .intellij.util.EnvironmentUtil - loading shell env: /bin/bash -l -i -c '/Applications/IntelliJ IDEA CE.app/Contents/bin/printenv.py' '/private/var/folders/_k/vs71smvn6r792p8csvwvtsgn_bg4w7/T/intellij-shell-env.tmp'
2020-09-10 07:06:20,357 [     75]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 69 ms
2020-09-10 07:06:20,387 [    105]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-193.6015.39, 20 Jan 2020 22:12)
2020-09-10 07:06:20,387 [    105]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (10.14.6, x86_64)
2020-09-10 07:06:20,388 [    106]   INFO -        #com.intellij.idea.Main - JRE: 11.0.5+10-b520.30 (JetBrains s.r.o)
2020-09-10 07:06:20,388 [    106]   INFO -        #com.intellij.idea.Main - JVM: 11.0.5+10-b520.30 (OpenJDK 64-Bit Server VM)
2020-09-10 07:06:20,388 [    106]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx2048m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -XX:CICompilerCount=2 -Dsun.io.useCanonPrefixCache=false -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Djdk.attach.allowAttachSelf=true -Dkotlinx.coroutines.debug=off -Djdk.module.illegalAccess.silent=true -XX:+UseCompressedOops -Dfile.encoding=UTF-8 -XX:ErrorFile=/Users/woodb03/java_error_in_idea_%p.log -XX:HeapDumpPath=/Users/woodb03/java_error_in_idea.hprof -Djb.vmOptionsFile=/Users/woodb03/Library/Preferences/IdeaIC2019.3/idea.vmoptions -Didea.home.path=/Applications/IntelliJ IDEA CE.app/Contents -Didea.executable=idea -Didea.platform.prefix=Idea -Didea.paths.selector=IdeaIC2019.3
2020-09-10 07:06:20,388 [    106]   INFO -        #com.intellij.idea.Main - charsets: JNU=UTF-8 file=UTF-8
2020-09-10 07:06:20,421 [    139]   INFO - .intellij.util.EnvironmentUtil - shell environment loaded (14 vars)
2020-09-10 07:06:20,460 [    178]   INFO - .intellij.util.EnvironmentUtil - LC_CTYPE=en_US.UTF-8
2020-09-10 07:06:20,545 [    263]   INFO - ntellij.idea.ApplicationLoader - CPU cores: 8; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@2b823b7a[Running, parallelism = 7, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@414f8d3b
2020-09-10 07:06:20,663 [    381]   INFO - llij.ide.plugins.PluginManager - Plugin "Groovy" misses optional descriptor duplicates-groovy.xml
2020-09-10 07:06:20,664 [    382]   INFO - llij.ide.plugins.PluginManager - Plugin "Groovy" misses optional descriptor duplicates-detection-groovy.xml
2020-09-10 07:06:20,742 [    460]   INFO - llij.ide.plugins.PluginManager - Plugin "Java" misses optional descriptor profiler-java.xml
2020-09-10 07:06:20,790 [    508]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Android Support (10.3.5), Ant (193.6015.39), Bytecode Viewer (193.6015.39), ChangeReminder (193.6015.39), Configuration Script (193.6015.39), Copyright (193.6015.39), Coverage (193.6015.39), Eclipse Interoperability (193.6015.39), EditorConfig (193.6015.39), Git (193.6015.39), GitHub (193.6015.39), Gradle (193.6015.39), Gradle-Java (193.6015.39), Gradle-Maven (193.6015.39), Groovy (193.6015.39), IDEA CORE (193.6015.39), IntelliLang (193.6015.39), JUnit (193.6015.39), Java (193.6015.39), Java Bytecode Decompiler (193.6015.39), Java IDE Customization (193.6015.39), Java Internationalization (193.6015.39), Java Stream Debugger (193.6015.39), JavaFX (193.6015.39), Kotlin (1.3.61-release-IJ2019.3-1), Machine Learning Code Completion (193.6015.39), Markdown (193.6015.39), Maven (193.6015.39), Mercurial (193.6015.39), Plugin DevKit (193.6015.39), Properties (193.6015.39), Settings Repository (193.6015.39), Shell Script (193.6015.39), Smali Support (193.6015.39), Subversion (193.6015.39), Task Management (193.6015.39), Terminal (193.6015.39), TestNG (193.6015.39), TextMate bundles (193.6015.39), UI Designer (193.6015.39), XPathView + XSLT (193.6015.39), XSLT Debugger (193.6015.39), YAML (193.6015.39)
2020-09-10 07:06:20,790 [    508]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Smart Tomcat (3.7.2)
2020-09-10 07:06:21,186 [    904]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=1961
2020-09-10 07:06:21,250 [    968]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=13, fontScale=1.0; restored: fontSize=13, fontScale=1.0
2020-09-10 07:06:21,314 [   1032]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0
2020-09-10 07:06:21,362 [   1080]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/IntelliJ IDEA CE.app/Contents/bin/fsnotifier
2020-09-10 07:06:21,383 [   1101]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational.
2020-09-10 07:06:21,384 [   1102]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63343
2020-09-10 07:06:21,437 [   1155]   INFO - gs.impl.UpdateCheckerComponent - channel: release
2020-09-10 07:06:21,685 [   1403]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized
2020-09-10 07:06:21,971 [   1689]   INFO - pl$FileIndexDataInitialization - Initialization done: 708
2020-09-10 07:06:22,070 [   1788]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings.
2020-09-10 07:06:22,099 [   1817]   INFO - exImpl$StubIndexInitialization - Initialization done: 128
2020-09-10 07:06:22,111 [   1829]   INFO - pl.projectlevelman.NewMappings - VCS Root: [Git] - [<Project>]
2020-09-10 07:06:23,249 [   2967]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found
2020-09-10 07:06:24,383 [   4101]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.kotlin.idea.highlighter.KotlinDefaultHighlightingSettingsProvider
2020-09-10 07:06:24,829 [   4547]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 1315ms; general responsiveness: ok; EDT responsiveness: 2/2 sluggish
2020-09-10 07:06:24,939 [   4657]   INFO - m.intellij.ui.mac.touchbar.NST - nst library works properly, successfully created and released native touchbar object
2020-09-10 07:06:25,366 [   5084]   INFO - tartup.impl.StartupManagerImpl - /Users/woodb03/projects/oi-dashboard/.idea case-sensitivity: expected=false actual=false
2020-09-10 07:06:25,426 [   5144]   INFO -  #git4idea.commands.GitHandler - [.] git version
2020-09-10 07:06:25,448 [   5166]   INFO -  #git4idea.commands.GitHandler - git version 2.17.1
2020-09-10 07:06:25,451 [   5169]   INFO - pl.projectlevelman.NewMappings - Mapped Roots: 1
2020-09-10 07:06:25,454 [   5172]   INFO - ea.config.GitExecutableManager - Git version for /usr/local/bin/git : 2.17.1
2020-09-10 07:06:25,623 [   5341]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 3961 ms
2020-09-10 07:06:25,886 [   5604]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 2093ms; general responsiveness: ok; EDT responsiveness: 2/2 sluggish
2020-09-10 07:06:28,185 [   7903]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2297ms; general responsiveness: ok; EDT responsiveness: ok
2020-09-10 07:06:30,966 [  10684]   INFO - CompilerWorkspaceConfiguration - Available processors: 8
2020-09-10 07:06:34,780 [  14498]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 476 millis (read time: 471)
2020-09-10 07:06:46,805 [  26523]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2020-09-10 07:06:48,544 [  28262]   INFO - llij.lang.ant.ReflectedProject - org.apache.tools.ant.Project
java.lang.ClassNotFoundException: org.apache.tools.ant.Project
                at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:307)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
                at com.intellij.lang.ant.ReflectedProject.<init>(ReflectedProject.java:86)
                at com.intellij.lang.ant.ReflectedProject.getProject(ReflectedProject.java:70)
                at org.jetbrains.plugins.groovy.gant.AntTasksProvider$AntClassLoader.lambda$new$0(AntTasksProvider.java:131)
                at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-10 07:09:25,193 [ 184911]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 2306 ms
2020-09-10 07:09:25,485 [ 185203]   INFO - llij.lang.ant.ReflectedProject - org.apache.tools.ant.Project
java.lang.ClassNotFoundException: org.apache.tools.ant.Project
                at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:307)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
                at com.intellij.lang.ant.ReflectedProject.<init>(ReflectedProject.java:86)
                at com.intellij.lang.ant.ReflectedProject.getProject(ReflectedProject.java:70)
                at org.jetbrains.plugins.groovy.gant.AntTasksProvider$AntClassLoader.lambda$new$0(AntTasksProvider.java:131)
                at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-10 07:09:27,907 [ 187625]   INFO - org.jetbrains.io.BuiltInServer - web server stopped
2020-09-10 07:09:27,915 [ 187633]   INFO - Types.impl.FileTypeManagerImpl - 41 auto-detected files. Detection took 33 ms
2020-09-10 07:09:27,916 [ 187634]   INFO - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 0
2020-09-10 07:09:27,917 [ 187635]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN
2020-09-10 07:09:27,928 [ 187646]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN
2020-09-10 07:09:27,928 [ 187646]   INFO - newvfs.persistent.PersistentFS - VFS dispose started
2020-09-10 07:09:27,940 [ 187658]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed
2020-09-10 07:09:27,940 [ 187658]   INFO - stubs.SerializationManagerImpl - START StubSerializationManager SHUTDOWN
2020-09-10 07:09:27,940 [ 187658]   INFO - stubs.SerializationManagerImpl - END StubSerializationManager SHUTDOWN
2020-09-10 07:09:27,942 [ 187660]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
2020-09-10 07:09:27,942 [ 187660]   INFO - org.jetbrains.io.BuiltInServer - web server stopped

**Comment by zengkid** [comment]
have you checked your JDK already install in your project?

**Comment by bcwood123** [comment]
I don't understand the question.

**Comment by bcwood123** [comment]
![Screen Shot 2020-09-10 at 8 04 27 AM](https://user-images.githubusercontent.com/10818036/92751702-13dc9800-f33d-11ea-9d4b-43e41ee79e35.png)

**Comment by bcwood123** [comment]
I wonder why the "11" is red in the java version.

**Comment by zengkid** [comment]
@bcwood123 it mean that your 11 java is invalid. please try to edit and correct the jdk 11 path

**Comment by bcwood123** [comment]
I have been switching back and forth between Java 8 and Java 11, my Mac is  locked down by my company, and when I install one version of Java it replaces the other.  So currently I only have 8.  This whole exercise was to use Java 11, but I am working on other projects which necessitate having 8 installed.  Also, Tomcat 9 suddenly appeared on the Tomcat dropdown, so I don't know what happened.  This can be closed, since the original issue no longer exists.
