### ISSUE TITLE
I got an unknown error using the Idea Community version

### ISSUE THREAD

**Issue by Zzzzzzj** [zengkid/SmartTomcat#62]
It's like description , I got an 'unknown error' when I started a project. Where I can find smarttomcart Log on my computer?
I tried to restart idea and computer,but it's not used,the tips is still,
![image](https://user-images.githubusercontent.com/13479306/101562183-de118300-3a01-11eb-9aba-16adb7129dbb.png)

```
9:20	Error running 'xxxxx': Unknown error
```

**Comment by zengkid** [comment]
@Zzzzzzj what's the xxxx mean? project name or others?

**Comment by Zzzzzzj** [comment]
yes, it's my project name . it is sensitive because it's mercantile, so I use 'xxxx' to replace it

**Comment by zengkid** [comment]
which idea version?
please check idea log 
%localappdata%\JetBrains\IdeaICxxxx\log

**Comment by Zzzzzzj** [comment]
The version is 2019.3.1 

which file I should check ? Is The log path ` C:\Users\{username}\.IdeaIC2019.3\system\log `  ?

I check this , and find some tomcat error ,like this : 
``` 
2020-11-24 10:24:14,940 [92224436]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
java.lang.RuntimeException
	at com.poratu.idea.plugins.tomcat.conf.AppCommandLineState.createJavaParameters(AppCommandLineState.java:127)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:34)
	at com.intellij.debugger.impl.GenericDebuggerRunner.createContentDescriptor(GenericDebuggerRunner.java:55)
	at com.intellij.debugger.impl.GenericDebuggerRunner.doExecute(GenericDebuggerRunner.java:49)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:56)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:56)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at com.poratu.idea.plugins.tomcat.conf.AppCommandLineState.updateServerConf(AppCommandLineState.java:168)
	at com.poratu.idea.plugins.tomcat.conf.AppCommandLineState.createJavaParameters(AppCommandLineState.java:116)
	... 29 more
``` 

It's the reason?

**Comment by Zzzzzzj** [comment]
and I couldn't find the directory which path is `%localappdata%\JetBrains` , it doesn't exist

**Comment by zengkid** [comment]
May I know which version for plugins SmartTomcat ?

**Comment by Zzzzzzj** [comment]
The plugin version is 3.8.2 , and I tried to use it which version are 3.7 and 3.6 , but error is still exists

**Comment by zengkid** [comment]
Have you edit the tomcat server.xml file?

**Comment by zengkid** [comment]
for 3.8.2, the error null pointer exception isn't match the error log line number.

**Comment by Zzzzzzj** [comment]
oh yes .... Just now I restored the original configuration , plugin has worked ....  Which configuration will cause this problem?

**Comment by Zzzzzzj** [comment]
> for 3.8.2, the error null pointer exception isn't match the error log line number.

but the Log time is match ...

**Comment by zengkid** [comment]
> oh yes .... Just now I restored the original configuration , plugin has worked .... Which configuration will cause this problem?

yes. the plugin will copy the server.xml and update it. you must run tomcat standalone and check the tomcat work or not.

if run tomcat standalone successfully, but run SmartTomcat fail, then the plugin has some issue. please provider what do you changed.

**Comment by Zzzzzzj** [comment]
> > oh yes .... Just now I restored the original configuration , plugin has worked .... Which configuration will cause this problem?
> 
> yes. the plugin will copy the server.xml and update it. you must run tomcat standalone and check the tomcat work or not.
> 
> if run tomcat standalone successfully, but run SmartTomcat fail, then the plugin has some issue. please provider what do you changed.

ok~the old config file is delete already and i have no copy. thx to answer for me. if the error show again I will provide the config  to you
