### ISSUE TITLE
Intermittent fail to start tomcat

### ISSUE THREAD

**Issue by clemilsonmorais** [zengkid/SmartTomcat#79]
When I start my tomcat, sometimes I get the following error described in the stack trace below.
The weird thing is: after some retries, the tomcat is correctly started.

I'm using the Intellij Community version 2021.3.2 (Build #IC-213.6777.52, built on January 28, 2022) and the tomcat 9.0.58 (I've tried the tomcat version 8.5 but I got the same error).

```29-Jan-2022 20:10:32.333 INFORMAÇÕES [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.58]
29-Jan-2022 20:10:37.526 GRAVE [main] org.apache.catalina.core.ContainerBase.startInternal A child container failed during start
	java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:926)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
http://localhost:8080/teste
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		... 21 more
	Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/teste] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
		at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2404)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2342)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2294)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:2264)
		at org.apache.catalina.startup.ContextConfig.scanWebXmlFragment(ContextConfig.java:2172)
		at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:2152)
		at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1408)
		at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1303)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:986)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 27 more
29-Jan-2022 20:10:37.542 GRAVE [main] org.apache.catalina.core.ContainerBase.startInternal A child container failed during start
	java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:926)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: org.apache.catalina.LifecycleException: A child container failed during start
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:938)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		... 13 more
	Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:926)
		... 21 more
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		... 21 more
	Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/teste] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
		at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2404)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2342)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2294)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:2264)
		at org.apache.catalina.startup.ContextConfig.scanWebXmlFragment(ContextConfig.java:2172)
		at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:2152)
		at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1408)
		at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1303)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:986)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 27 more
29-Jan-2022 20:10:37.558 GRAVE [main] org.apache.catalina.startup.Catalina.start O componente Server requerido falhou ao iniciar, por isso, o Tomcat não pode iniciar
	org.apache.catalina.LifecycleException: A child container failed during start
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:938)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:926)
		... 13 more
	Caused by: org.apache.catalina.LifecycleException: A child container failed during start
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:938)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		... 13 more
	Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:926)
		... 21 more
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		... 21 more
	Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/teste] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
		at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2404)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2342)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2294)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:2264)
		at org.apache.catalina.startup.ContextConfig.scanWebXmlFragment(ContextConfig.java:2172)
		at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:2152)
		at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1408)
		at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1303)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:986)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 27 more
29-Jan-2022 20:10:37.573 INFORMAÇÕES [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
29-Jan-2022 20:10:37.573 INFORMAÇÕES [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
29-Jan-2022 20:10:37.573 INFORMAÇÕES [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
29-Jan-2022 20:10:37.573 ADVERTÊNCIA [main] org.apache.catalina.deploy.NamingResourcesImpl.cleanUp Failed to retrieve JNDI naming context for container [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/teste]] so no cleanup was performed for that container
	javax.naming.NamingException: No naming context bound to this class loader
		at org.apache.naming.ContextBindings.getClassLoader(ContextBindings.java:268)
		at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1020)
		at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1003)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5492)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:293)
		at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:826)
		at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1033)
		at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
		at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:826)
		at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1033)
		at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
		at org.apache.catalina.core.StandardService.destroyInternal(StandardService.java:579)
		at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
		at org.apache.catalina.core.StandardServer.destroyInternal(StandardServer.java:1050)
		at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:776)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)

Process finished with exit code 0
```

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。

**Comment by zengkid** [comment]
@clemilsonmorais 
please try to deploy to tomcat, and check if work on tomcat alone or not.

**Comment by clemilsonmorais** [comment]
> @clemilsonmorais please try to deploy to tomcat, and check if work on tomcat alone or not.

When I use the configuration of Intellij Ultimate or when I deploy the tomcat standalone it works fine.

**Comment by zengkid** [comment]
> > @clemilsonmorais please try to deploy to tomcat, and check if work on tomcat alone or not.
> 
> When I use the configuration of Intellij Ultimate or when I deploy the tomcat standalone it works fine.

could you share your JNDI config file?

**Comment by clemilsonmorais** [comment]
> could you share your JNDI config file?

I'm not sure if I have this config file, but I'm using the default settings, as described on the example

**Comment by zengkid** [comment]
> > could you share your JNDI config file?
> 
> I'm not sure if I have this config file, but I'm using the default settings, as described on the example

could you provide more detail, or share your mini simple project.
